### ISSUE TITLE
certificate

### ISSUE THREAD

**Issue by katilp** [katilp/data-curation#1]
Install the certificate on .globus directory on lxplus and test

(https://twiki.cern.ch/twiki/bin/view/CMSPublic/WorkBookStartingGrid#ObtainingCert)

**Comment by mokotus** [comment]
I have done the steps as described in "Obtaining and installing your Certificate"-section of the linked page and I have a few questions:
- How exactly can I "test" the certificate in the .globus folder? There doesn't seem to be any specific command on the linked page.
- Do I (or users in general) repeat this process every time when beginning to work on something (since those cert files aren't saved on lxplus)?

**Comment by katilp** [comment]
If `voms-proxy-init --rfc --voms cms` it should be fine. What's the output of that?

**Comment by katilp** [comment]
The cert files, once you have them in the .globus directory remain there. They have to be renewed once/year. For the tasks that need the certificate, you will need to do voms-proxy-init before.

**Comment by mokotus** [comment]
Alright, good to know!
The command seems to work fine:
```
[mpiitsal@lxplus767 .globus]$ voms-proxy-init --rfc --voms cms
Enter GRID pass phrase for this identity:
Contacting lcg-voms2.cern.ch:15002 [/DC=ch/DC=cern/OU=computers/CN=lcg-voms2.cern.ch] "cms"...
Remote VOMS server contacted succesfully.


Created proxy in /tmp/x509up_u131782.

Your proxy is valid until Sat Mar 14 01:13:55 CET 2020
```
